FROM node:22-slim
WORKDIR /app
RUN corepack enable
COPY package.json yarn.lock .yarnrc.yml ./
RUN yarn install --immutable
COPY . .
# Vite bakes these into the bundle at build time; pass as --build-arg.
ARG REACT_APP_STAGE=custom
ARG REACT_APP_API_BASE
ARG REACT_APP_CONTENT_ROOT
ARG REACT_APP_MESSAGING_API_SOCKET
ARG REACT_APP_B1_ROOT
ARG REACT_APP_B1ADMIN_ROOT
ARG REACT_APP_GOOGLE_ANALYTICS
ENV REACT_APP_STAGE=$REACT_APP_STAGE \
    REACT_APP_API_BASE=$REACT_APP_API_BASE \
    REACT_APP_CONTENT_ROOT=$REACT_APP_CONTENT_ROOT \
    REACT_APP_MESSAGING_API_SOCKET=$REACT_APP_MESSAGING_API_SOCKET \
    REACT_APP_B1_ROOT=$REACT_APP_B1_ROOT \
    REACT_APP_B1ADMIN_ROOT=$REACT_APP_B1ADMIN_ROOT \
    REACT_APP_GOOGLE_ANALYTICS=$REACT_APP_GOOGLE_ANALYTICS
RUN yarn build
EXPOSE 3101
CMD ["yarn", "serve"]
