on:
  push:
    branches:
      [
        main
      ]
  workflow_dispatch:

name: Deploy Staging

env:
  SERVERLESS_ACCESS_KEY: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy Staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          submodules: "true"

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          aws-access-key-id: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Setup Serverless
        run:
          |
          export SERVERLESS_ACCESS_KEY="$SERVERLESS_ACCESS_KEY"

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Deploy
        run: yarn deploy-staging
